"""add auto_ack_precheck/postcheck flags to upgrade_jobs

Revision ID: 1a00e3d159ca
Revises: 41eaba3f36ac
Create Date: 2026-05-18 20:32:55.140794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1a00e3d159ca'
down_revision: Union[str, None] = '41eaba3f36ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Default existing rows to False (preserves prior behavior of always
    # parking at the override gate). server_default lets the NOT NULL
    # constraint be added without a separate UPDATE pass for old jobs.
    op.add_column(
        'upgrade_jobs',
        sa.Column('auto_ack_precheck_failures', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'upgrade_jobs',
        sa.Column('auto_ack_postcheck_failures', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upgrade_jobs', 'auto_ack_postcheck_failures')
    op.drop_column('upgrade_jobs', 'auto_ack_precheck_failures')
    # ### end Alembic commands ###
