"""add ip_address to devices

Revision ID: 32de244f9ab1
Revises: 0b467919e863
Create Date: 2026-05-08 22:02:28.952232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '32de244f9ab1'
down_revision: Union[str, None] = '0b467919e863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('ip_address', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'ip_address')
    # ### end Alembic commands ###
