"""add snapshot + snapshot_diff tables

Revision ID: 3b761468c484
Revises: 97b0410a856e
Create Date: 2026-05-16 06:25:10.933183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3b761468c484'
down_revision: Union[str, None] = '97b0410a856e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('PRE_UPGRADE', 'POST_UPGRADE', 'AD_HOC', name='snapshot_kind'), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('pan_os_version', sa.String(length=64), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['device_upgrade_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_device_id'), 'snapshots', ['device_id'], unique=False)
    op.create_index(op.f('ix_snapshots_taken_at'), 'snapshots', ['taken_at'], unique=False)
    op.create_index(op.f('ix_snapshots_task_id'), 'snapshots', ['task_id'], unique=False)
    op.create_table('snapshot_diffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('left_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('right_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('all_passed', sa.Boolean(), nullable=False),
    sa.Column('failing_areas', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['left_snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['device_upgrade_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshot_diffs_left_snapshot_id'), 'snapshot_diffs', ['left_snapshot_id'], unique=False)
    op.create_index(op.f('ix_snapshot_diffs_right_snapshot_id'), 'snapshot_diffs', ['right_snapshot_id'], unique=False)
    op.create_index(op.f('ix_snapshot_diffs_task_id'), 'snapshot_diffs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshot_diffs_task_id'), table_name='snapshot_diffs')
    op.drop_index(op.f('ix_snapshot_diffs_right_snapshot_id'), table_name='snapshot_diffs')
    op.drop_index(op.f('ix_snapshot_diffs_left_snapshot_id'), table_name='snapshot_diffs')
    op.drop_table('snapshot_diffs')
    op.drop_index(op.f('ix_snapshots_task_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_taken_at'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_device_id'), table_name='snapshots')
    op.drop_table('snapshots')
    # Postgres keeps the enum type around after the table is gone; drop it
    # explicitly so a downgrade-then-upgrade cycle doesn't trip "type already exists".
    sa.Enum(name='snapshot_kind').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
