"""add precheck_runs and device.licenses

Revision ID: 48e7b2e595e4
Revises: 3cebc2969270
Create Date: 2026-05-08 23:07:15.203841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '48e7b2e595e4'
down_revision: Union[str, None] = '3cebc2969270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precheck_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('ran_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ran_by_user_id', sa.Integer(), nullable=True),
    sa.Column('overall_severity', sa.Enum('PASS', 'WARN', 'FAIL', 'SKIP', name='severity'), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('warn_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('skip_count', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ran_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_precheck_runs_device_id'), 'precheck_runs', ['device_id'], unique=False)
    op.create_index(op.f('ix_precheck_runs_ran_at'), 'precheck_runs', ['ran_at'], unique=False)
    op.add_column('devices', sa.Column('licenses', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'licenses')
    op.drop_index(op.f('ix_precheck_runs_ran_at'), table_name='precheck_runs')
    op.drop_index(op.f('ix_precheck_runs_device_id'), table_name='precheck_runs')
    op.drop_table('precheck_runs')
    # ### end Alembic commands ###
