"""add stage runs and staged_version on device

Revision ID: 50422823c283
Revises: 58042c6b89f4
Create Date: 2026-05-09 01:46:37.125885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '50422823c283'
down_revision: Union[str, None] = '58042c6b89f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # The `severity` ENUM was already created by the precheck migration.
    # Use postgresql.ENUM with create_type=False AND set _create_managed=False
    # via the bind hint so create_table doesn't emit a duplicate CREATE TYPE.
    bind = op.get_bind()
    severity_enum = postgresql.ENUM(
        'PASS', 'WARN', 'FAIL', 'SKIP',
        name='severity',
        create_type=False,
    )
    # Defensive: only create if it doesn't already exist (it should, from the
    # precheck migration). This guards against any earlier partial state.
    severity_enum.create(bind, checkfirst=True)

    op.create_table(
        'bulk_stage_runs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('started_by_user_id', sa.Integer(), nullable=True),
        sa.Column('target_count', sa.Integer(), nullable=False),
        sa.Column('version', sa.String(length=64), nullable=False),
        sa.Column('cancelled', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['started_by_user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'device_stage_runs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('bulk_run_id', sa.Integer(), nullable=True),
        sa.Column('device_id', sa.Integer(), nullable=False),
        sa.Column('version', sa.String(length=64), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('outcome', severity_enum, nullable=False),
        sa.Column('error', sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(['bulk_run_id'], ['bulk_stage_runs.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_device_stage_runs_bulk_run_id'), 'device_stage_runs', ['bulk_run_id'], unique=False)
    op.create_index(op.f('ix_device_stage_runs_device_id'), 'device_stage_runs', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_stage_runs_started_at'), 'device_stage_runs', ['started_at'], unique=False)
    op.add_column('devices', sa.Column('staged_version', sa.String(length=64), nullable=True))
    op.add_column('devices', sa.Column('staged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('devices', sa.Column('staged_error', sa.String(length=2000), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'staged_error')
    op.drop_column('devices', 'staged_at')
    op.drop_column('devices', 'staged_version')
    op.drop_index(op.f('ix_device_stage_runs_started_at'), table_name='device_stage_runs')
    op.drop_index(op.f('ix_device_stage_runs_device_id'), table_name='device_stage_runs')
    op.drop_index(op.f('ix_device_stage_runs_bulk_run_id'), table_name='device_stage_runs')
    op.drop_table('device_stage_runs')
    op.drop_table('bulk_stage_runs')
    # ### end Alembic commands ###
