"""add bulk_precheck_runs and bulk_run_id

Revision ID: 58042c6b89f4
Revises: 48e7b2e595e4
Create Date: 2026-05-09 00:49:09.795315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '58042c6b89f4'
down_revision: Union[str, None] = '48e7b2e595e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_precheck_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_by_user_id', sa.Integer(), nullable=True),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('checks_requested', sa.JSON(), nullable=False),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['started_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('precheck_runs', sa.Column('bulk_run_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_precheck_runs_bulk_run_id'), 'precheck_runs', ['bulk_run_id'], unique=False)
    op.create_foreign_key(None, 'precheck_runs', 'bulk_precheck_runs', ['bulk_run_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'precheck_runs', type_='foreignkey')
    op.drop_index(op.f('ix_precheck_runs_bulk_run_id'), table_name='precheck_runs')
    op.drop_column('precheck_runs', 'bulk_run_id')
    op.drop_table('bulk_precheck_runs')
    # ### end Alembic commands ###
