"""initial schema

Revision ID: c4e264510ef5
Revises: 
Create Date: 2026-05-08 21:34:12.009278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c4e264510ef5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('auth_type', sa.Enum('API_KEY', 'USERPASS', name='auth_type'), nullable=False),
    sa.Column('scope', sa.Enum('DEVICE', 'PANORAMA', name='credential_scope'), nullable=False),
    sa.Column('encrypted_secret', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('panos_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panos_images_version'), 'panos_images', ['version'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('panoramas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('proxy_upgrades', sa.Boolean(), nullable=False),
    sa.Column('verify_tls', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('upgrade_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_version', sa.String(length=64), nullable=False),
    sa.Column('workflow', sa.Enum('FULL', 'PARTIAL', name='workflow_type'), nullable=False),
    sa.Column('workflow_stages', sa.JSON(), nullable=True),
    sa.Column('require_failover_confirmation', sa.Boolean(), nullable=False),
    sa.Column('require_primary_upgrade_confirmation', sa.Boolean(), nullable=False),
    sa.Column('auto_failback', sa.Boolean(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('device_pull_image', sa.Boolean(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'RUNNING', 'AWAITING_CONFIRMATION', 'COMPLETED', 'FAILED', 'ABORTED', name='job_state'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['panos_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('serial', sa.String(length=64), nullable=True),
    sa.Column('source', sa.Enum('DIRECT', 'PANORAMA', name='device_source'), nullable=False),
    sa.Column('panorama_id', sa.Integer(), nullable=True),
    sa.Column('credential_id', sa.Integer(), nullable=True),
    sa.Column('ha_peer_id', sa.Integer(), nullable=True),
    sa.Column('ha_role', sa.Enum('STANDALONE', 'ACTIVE', 'PASSIVE', 'UNKNOWN', name='ha_role'), nullable=False),
    sa.Column('device_group', sa.String(length=255), nullable=True),
    sa.Column('template_stack', sa.String(length=255), nullable=True),
    sa.Column('current_version', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('uptime', sa.String(length=64), nullable=True),
    sa.Column('ha_state', sa.String(length=32), nullable=True),
    sa.Column('ha_sync_state', sa.String(length=32), nullable=True),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('threat_version', sa.String(length=64), nullable=True),
    sa.Column('av_version', sa.String(length=64), nullable=True),
    sa.Column('wildfire_version', sa.String(length=64), nullable=True),
    sa.Column('url_filtering_version', sa.String(length=64), nullable=True),
    sa.Column('gp_client_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_refresh_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['ha_peer_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['panorama_id'], ['panoramas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('serial')
    )
    op.create_table('device_upgrade_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('ha_pair_key', sa.String(length=64), nullable=False),
    sa.Column('phase', sa.Enum('PENDING', 'PRECHECK', 'SNAPSHOT', 'DOWNLOADING_IMAGE', 'SUSPEND_SECONDARY', 'UPGRADE_SECONDARY', 'POSTCHECK_SECONDARY', 'AWAITING_FAILOVER_CONFIRM', 'FAILOVER', 'AWAITING_PRIMARY_UPGRADE_CONFIRM', 'UPGRADE_PRIMARY', 'POSTCHECK_PRIMARY', 'FAILBACK', 'REPORT', 'DONE', 'FAILED', name='task_phase'), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('confirmation_token', sa.String(length=64), nullable=True),
    sa.Column('tick_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['upgrade_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_upgrade_tasks_device_id'), 'device_upgrade_tasks', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_upgrade_tasks_ha_pair_key'), 'device_upgrade_tasks', ['ha_pair_key'], unique=False)
    op.create_index(op.f('ix_device_upgrade_tasks_job_id'), 'device_upgrade_tasks', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_upgrade_tasks_job_id'), table_name='device_upgrade_tasks')
    op.drop_index(op.f('ix_device_upgrade_tasks_ha_pair_key'), table_name='device_upgrade_tasks')
    op.drop_index(op.f('ix_device_upgrade_tasks_device_id'), table_name='device_upgrade_tasks')
    op.drop_table('device_upgrade_tasks')
    op.drop_table('devices')
    op.drop_table('upgrade_jobs')
    op.drop_table('panoramas')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_panos_images_version'), table_name='panos_images')
    op.drop_table('panos_images')
    op.drop_table('credentials')
    # ### end Alembic commands ###
