"""add downloaded_versions to devices

Revision ID: 635e05884c54
Revises: 50422823c283
Create Date: 2026-05-09 18:56:09.006149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '635e05884c54'
down_revision: Union[str, None] = '50422823c283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('downloaded_versions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'downloaded_versions')
    # ### end Alembic commands ###
